add ipfs-cluster installation

diff --git a/install b/install
--- a/install
+++ b/install
@@ -47,6 +47,50 @@ ipfs_destination=/usr/local/bin/ipfs
 tar xzf $tar_gz_destination -C /tmp
 sudo install /tmp/go-ipfs/ipfs $ipfs_destination
 
+# Download and install IPFS Cluster Service
+ipsvc_arch=${2-"linux-arm"}
+ipsvc_version=$(curl -s https://dist.ipfs.io/ipfs-cluster-service/versions | tail -1)
+ipsvc_version=${1-$ipsvc_version}
+ipsvc_version="v${ipsvc_version#v}"
+
+echo ">>> Installing IPFS Cluster Service version $ipsvc_version"
+
+tar_gz_destination=/tmp/go-ipfs_${ipsvc_version}_${ipsvc_arch}.tar.gz
+wget "https://dist.ipfs.io/ipfs-cluster-service/${ipsvc_version}/ipfs-cluster-service_${ipsvc_version}_${ipsvc_arch}.tar.gz" \
+  -q --show-progress \
+  -O $tar_gz_destination
+
+if [ ! -f $tar_gz_destination ]; then
+  echo ">>> Failed to download IPFS Cluster Service"
+  exit 1
+fi
+
+ipsvc_destination=/usr/local/bin/ipfs-cluster-service
+tar xzf $tar_gz_destination -C /tmp
+sudo install /tmp/ipfs-cluster-service/ipfs-cluster-service $ipfs_destination
+
+# Download and install IPFS Cluster Ctl
+ipctl_arch=${2-"linux-arm"}
+ipctl_version=$(curl -s https://dist.ipfs.io/ipfs-cluster-ctl/versions | tail -1)
+ipctl_version=${1-$ipctl_version}
+ipctl_version="v${ipctl_version#v}"
+
+echo ">>> Installing IPFS Cluster Ctl version $ipctl_version"
+
+tar_gz_destination=/tmp/go-ipfs_${ipctl_version}_${ipctl_arch}.tar.gz
+wget "https://dist.ipfs.io/ipfs-cluster-service/${ipctl_version}/ipfs-cluster-service_${ipctl_version}_${ipctl_arch}.tar.gz" \
+  -q --show-progress \
+  -O $tar_gz_destination
+
+if [ ! -f $tar_gz_destination ]; then
+  echo ">>> Failed to download IPFS Cluster Ctl"
+  exit 1
+fi
+
+ipfs_destination=/usr/local/bin/ipfs-cluster-ctl
+tar xzf $tar_gz_destination -C /tmp
+sudo install /tmp/ipfs-cluster-ctl/ipfs-cluster-ctl $ipfs_destination
+
 echo ">>> Starting IPFS"
 
 # Maybe initialize IPFS
